import time
import streamlit as st
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.graph import MessagesState, StateGraph, START, END
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser
from typing_extensions import TypedDict, List
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.graph import MessagesState, StateGraph, START, END
from langchain_core.messages import HumanMessage, SystemMessage
from concurrent.futures import *
import ast
import json
from utils.utils import getCohereLLM
from agents.testAgent import getResponseFromTestAgent
from utils.AgentState import AgentState
import re
from utils.utils import promptCreationForDataFrame
from utils.utils import getDataFrameObject

routerPrompt = PromptTemplate(
    template="""
    You are a Python data analysis expert.

    Your job is to write a clean and executable Python code snippet based on the user's request.
    
    Assume the following:
    - A pandas DataFrame named `df` is already loaded and available.
    - Do not explain anything — return only the code.
    - Focus on using pandas and matplotlib/seaborn as needed.
    
    User request:
    {user_prompt}
    
    Important Instructions:
    -Return only code in python language with correct syntax and correct indentation.
    -Donot give any other prefix "python" or other , suffix to the code in the response except the code.Do not write unnecessary
    suggestions in the code and explanations.
    -Donot write any print statements and log statements
    -Write the code in single python script (not in multiple chunks)
    -Store the final answer to the "result" variable.
    """,
    input_variables=["user_prompt"],
)

llm = getCohereLLM()

query_decomposer = routerPrompt | llm

def getGraph():
    graph = StateGraph(AgentState)

    # Add nodes
    graph.add_node("code_generator", codeGenerator)
    graph.add_node("code_extractor", codeExtraction)
    graph.add_node("code_executor", execCode)
    graph.add_node("summarize_response",summarizeResponse)

    # Routing logic
    graph.set_entry_point("code_generator")
    graph.add_edge("code_generator","code_extractor")
    graph.add_edge("code_extractor","code_executor")
    graph.add_edge("code_executor","summarize_response")
    graph.add_edge("summarize_response",END)

    flow = graph.compile()
    return flow


def summarizeResponse(state:AgentState):
    """It is a python agent that summarizes the user prompt and the solution"""

    user_query = state["user_input"]
    response1 = state["generation"]

    st = "Question : " + str(user_query) + "/n" + "Answer : " + str(response1)

    summarizePrompt = PromptTemplate(
        template="""
        You are a Python data analysis expert.

        Your goal is to generate a summarized response from the {user_prompt} which contains both user input and response generated by LLM.
        Donot mention about question and answer seperately.Consolidate both and give final summarize answer

        ### Rules:
        - **Write the output response in single sentence or para

        ---

        User request:
        {user_prompt}

        ### Output Format (Example):
        

        """,
        input_variables=["user_prompt"],
    )
    summarize_query_decomposer = summarizePrompt | llm

    response = summarize_query_decomposer.invoke({"user_prompt":st})

    return {
        "user_input" : state["user_input"],
        "steps" : state["steps"],
        "generation" : response.strip()
    }


def execCode(state: AgentState):
    """It is a python tool that used to execute the code that is extracted and return the response"""
    user_query = state["user_input"]
    code = state["generation"]

    #Logic to eval code
    a = 40;
    df = getDataFrameObject()
    context = {"df" : df}

    try:
        exec(code, {}, context)
        print(context)
        if "steps" in state:
            steps = state["steps"]
        else:
            steps = []
        steps.append("CodeAgent-CodeEvaluation")
        decision = context["result"]
        return {
            "user_input": user_query,
            "generation": decision,
            "steps": steps
        }
    except:
        return {
            "user_input": user_query,
            "generation": "Not able to execute code generated by LLM.Not able to find answer",
            "steps": state["steps"]
        }


def codeExtraction(state: AgentState):
    """It is a python code agent for a sales AI assistant, which extracts the code snippet from the generated response from code Generator agent"""
    user_query = state["user_input"]
    codeText = state["generation"]
    # Extract code between triple backticks or similar pattern
    code_blocks = re.findall(r"```(?:python)?\n(.*?)```", codeText, re.DOTALL)
    if code_blocks:
        # Join multiple code blocks if needed
        code_only = "\n".join(code_blocks).strip()
    else:
        code_only = codeText

    print(code_only)
    if "steps" in state:
        steps = state["steps"]
    else:
        steps = []
    steps.append("CodeAgent-CodeExtractor")
    decision = code_only
    return {
        "user_input": user_query,
        "generation": decision,
        "steps": steps
    }

def codeGenerator(state: AgentState):
    """It is a python code agent for a sales AI assistant, Which generates the code for given prompt using python tool"""
    user_query = state["user_input"]
    decision = query_decomposer.invoke({"user_prompt": user_query})
    if "steps" in state:
        steps = state["steps"]
    else:
        steps = []
    steps.append("CodeAgent-CodeGenerator")
    decision = decision
    return {
        "user_input": user_query,
        "generation": decision,
        "steps": steps
    }

def codeAgent(state: AgentState):
    """It is a python code agent for a sales AI assistant, Which generates the code for given prompt using python tool
    and then evaluate the code and get the response"""

    dataframeprompt = promptCreationForDataFrame()

    prompt1 = """
    You are a **brilliant Python data analysis expert**.

    Your job is to write a clean and executable Python code snippet based on the user's request.
    
    Assume the following:
    - A pandas DataFrame named `df` is already loaded and available.
    - Do not explain anything — return only the code.
    - Focus on using pandas and matplotlib/seaborn as needed.
    """

    prompt2 = """
    User request:
    {user_prompt}
    
    Important Instructions:
    -Return only code in python language with correct syntax and correct indentation , the entire code should be in "python cell"
    -Donot give any other prefix "python" or other , suffix to the code in the response except the code.Do not write unnecessary
    suggestions in the code and explanations.
    -Donot write any print statements and log statements
    -Write the code in single python script (not in multiple chunks)
    -Store the final answer to the "result" variable.
    """

    prompt_template = prompt1 + "/n" + dataframeprompt + "/n" + prompt2

    global routerPrompt
    codePrompt = PromptTemplate(
        template=prompt_template,
        input_variables=["user_prompt"],
    )
    global query_decomposer
    query_decomposer = codePrompt | llm

    user_query = state["user_input"]
    flow = getGraph()
    decision = flow.invoke(state)
    if "steps" in state:
        steps = state["steps"]
    else:
        steps = []
    steps.append("CodeAgent")
    decision = decision["generation"]
    return {
        "user_input": user_query,
        "generation": decision,
        "steps": steps
    }
