import time
import streamlit as st
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.graph import MessagesState, StateGraph, START, END
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser
from typing_extensions import TypedDict, List
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.graph import MessagesState, StateGraph, START, END
from langchain_core.messages import HumanMessage, SystemMessage
from concurrent.futures import *
import ast
import json
from utils.utils import getCohereLLM
from agents.testAgent import getResponseFromTestAgent
from utils.AgentState import AgentState
import re
from utils.utils import promptCreationForDataFrame
from agents.codeAgent import codeAgent

routerPrompt = PromptTemplate(
    template="""
    -Your goal is to generate a diverse list of **insightful sub questions of which gives sufficient meaning to the user input and practical data analysis questions** based on the {user_prompt}. These questions should help a business user understand trends, anomalies, and patterns.
        -Your task is to help break down a user’s high-level question into **a few clear, relevant sub-questions** (between 1 and 5), but **only as many as are actually useful**. Do **not** force exactly 5.

        ### Guidelines:
        - Output only as many questions as make sense — **stop if there are no more meaningful sub-questions**.
        - Do **not pad or make up weak or redundant questions to hit 5**.
        - Each sub-question should be specific, data-driven, and help explore the original question in more detail.
        - Never ever generate some extra unwanted questions that not at all related to user prompt
        
        ### Rules:
        - Focus on **descriptive** and **diagnostic** questions (e.g., “What?”, “Why?”, “How much?”).
        - Include a mix of **aggregations**, **comparisons**, **trends**, and **anomalies**.
        - Avoid vague or generic questions.
        - Prefer **business-relevant** framing ("Which region is underperforming?", not just "Show mean of X").
        - Limit to **1 question per line**, numbered.
        
        ### Assume the following:
        - A pandas DataFrame named `df` is already loaded and available.
    
    ---

    User request:
    {user_prompt}
    
    ### Output Format (Example):
    What is the total revenue per region?
    Which product category has the highest average sales?
    How has monthly sales trended over the past year?
    ...

    """,
    input_variables=["user_prompt"],
)

llm = getCohereLLM()

query_decomposer = routerPrompt | llm


def getGraph():
    graph = StateGraph(AgentState)

    # Add nodes
    graph.add_node("questions_generator", questionsGenerator)
    graph.add_node("questions_answers", questionsAnswers)
    graph.add_node("summarize_answer",summarizeResponse)

    # Routing logic
    graph.set_entry_point("questions_generator")
    graph.add_edge("questions_generator", "questions_answers")
    graph.add_edge("questions_answers", "summarize_answer")
    graph.add_edge("summarize_answer",END)

    flow = graph.compile()
    return flow


def summarizeResponse(state:AgentState):
    """It is a python agent that summarizes the user prompt and the solution"""

    summarizePrompt = PromptTemplate(
        template="""
        You are a Python data analysis expert.

        Your goal is to generate a summarized response from the {user_prompt} which contains both user input and response generated by LLM.Summarize all those sub questions and answers and give it as a summarized one. 
        Not specifically mentioning subquestion and answer.
        

        ### Rules:
        - **Write the summarized response in a paragraph

        ---

        User request:
        {user_prompt}

        ...

        """,
        input_variables=["user_prompt"],
    )
    summarize_query_decomposer = summarizePrompt | llm

    user_query = state["generation"]

    response = summarize_query_decomposer.invoke({"user_prompt":user_query})

    return {
        "user_input" : state["user_input"],
        "steps" : state["steps"],
        "generation" : response.strip()
    }


def questionsAnswers(state: AgentState):
    """It is a python insights agent for a sales AI assistant, which extracts the subquestion from the generated response and calls code generator agent to get response"""
    user_query = state["user_input"]
    questionsList = state["generation"]

    # Extract questions
    list_of_questions = [question.strip() for question in questionsList.strip().split('\n')]
    print(list_of_questions)

    def process_question(state,q):
        """Handles a single question and invokes the CRAG graph."""
        print("Handling subquestion:", q)
        user_query = q
        if "steps" in state:
            steps = state["steps"]
        else:
            steps = []
        steps.append("InsightsAgent-subQuestion")
        response = codeAgent({
                "user_input": user_query,
                "generation": "",
                "steps": steps,
                "tool" : ""
            })
        return response

    sub_answers = []
    #Use ThreadPoolExecutor for parallel processing of questions
    with ThreadPoolExecutor() as executor:
        # Submit tasks for each question
        futures = {executor.submit(process_question, state , q): q for q in list_of_questions}
        # Collect results as they complete
        for future in futures:
            try:
                sub_answers.append(future.result()["generation"])
                steps = future.result()["steps"]
            except Exception as e:
                sub_answers.append("Not a proper question to answer")

        steps.append("InsightAgent-SubAnswer")

    #map the question and answer in a single string
    questionAndAnswers = ""
    for q in range(len(list_of_questions)):
        st = 'Question : ' + str(list_of_questions[q])
        st = st + '/n' + 'Answer for above question is : ' + str(sub_answers[q])
        st = st + "/n"
        questionAndAnswers += st


    #create 2nd query template and invoke to get synopsis out of this






    return {
        "user_input": user_query,
        "generation": questionAndAnswers,
        "steps": steps
    }


def questionsGenerator(state: AgentState):
    """It is a python code agent for a sales AI assistant, Which generates the sufficient number of subquestions which can add up to a user question with atmost same meaning"""
    user_query = state["user_input"]
    decision = query_decomposer.invoke({"user_prompt": user_query})
    if "steps" in state:
        steps = state["steps"]
    else:
        steps = []
    steps.append("InsightsAgent-QuestionsGenerator")
    decision = decision
    return {
        "user_input": user_query,
        "generation": decision,
        "steps": steps
    }


def insightAgent(state: AgentState):
    """It is a python datascience insights agent for a sales AI assistant, Which generates the necessary insights related sub questions from the user
    input and then use code agent and then summarize those answers to get response"""

    dataframeprompt = promptCreationForDataFrame()

    prompt1 = """
    -based on dataframe give below , Your goal is to generate a diverse list of **insightful sub questions of which gives sufficient meaning to the user input and practical data analysis questions** based on the {user_prompt}. These questions should help a business user understand trends, anomalies, and patterns.
        -Your task is to help break down a user’s high-level question into **a few clear, relevant sub-questions** (between 1 and 5), but **only as many as are actually useful**. Do **not** force exactly 5.

        ### Assume the following:
        - A pandas DataFrame named `df` is already loaded and available.
        
        
        
        
    
    ---
    """

    prompt2 = """
    
    ### Guidelines:
    - Output only as many questions as make sense — **stop if there are no more meaningful sub-questions**.
    - Do **not pad or make up weak or redundant questions to hit 5**.
    - Each sub-question should be specific, data-driven, and help explore the original question in more detail.
    - Never ever generate some extra unwanted questions that not at all related to user prompt
    
    ### Rules:
    - Focus on **descriptive** and **diagnostic** questions (e.g., “What?”, “Why?”, “How much?”).
    - Include a mix of **aggregations**, **comparisons**, **trends**, and **anomalies**.
    - Avoid vague or generic questions.
    - Prefer **business-relevant** framing ("Which region is underperforming?", not just "Show mean of X").
    - Limit to **1 question per line**, numbered.
    - **If you donot find any subquestions, give the main prompt as a single subquestion**
    
    
    User request:
    {user_prompt}
    
    ### Output Format (Example):
    What is the total revenue per region?
    Which product category has the highest average sales?
    How has monthly sales trended over the past year?
    ...
    """

    prompt_template = dataframeprompt + "/n" + prompt1 + "/n" + prompt2

    global routerPrompt
    insightsPrompt = PromptTemplate(
        template=prompt_template,
        input_variables=["user_prompt"],
    )
    global query_decomposer
    query_decomposer = insightsPrompt | llm

    user_query = state["user_input"]
    flow = getGraph()
    decision = flow.invoke(state)
    if "steps" in state:
        steps = state["steps"]
    else:
        steps = []
    steps.append("InsightAgent")
    decision = decision["generation"]
    return {
        "user_input": user_query,
        "generation": decision,
        "steps": steps
    }
